name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      # 저장소 checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # snake svg 생성
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: tomchaccom
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#ffffff&color_dots=#161b22,#30363d,#6e7681,#bc8cff,#e2c5ff

      # output 브랜치로 push
      - name: Push Snake Animation to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
